# Generated by Django 4.2.7 on 2023-11-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='about',
            field=models.CharField(default='Default About Value', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='link',
            field=models.CharField(default='https://example.com', max_length=80),
            preserve_default=False,
        ),
    ]
